"""Site descriptions, categories and the default false-positive-prone list.

Sherlock's data.json says HOW to check a site but nothing about WHAT the site
is.  This module fills that gap: a hand-written map of site name -> (category,
description) for the well-known ones, plus keyword heuristics so every site
gets at least a category.  Names are matched loosely (case/punctuation
insensitive) so small renames in data.json still hit.
"""

import re
from urllib.parse import urlparse

CATEGORIES = [
    "Social", "Developer", "Gaming", "Video", "Music", "Art & Design", "Photo",
    "Forum", "Blogging", "Fediverse", "Security", "Business", "Shopping",
    "Dating", "Adult", "Education", "Books & Writing", "Sport & Outdoors",
    "Finance & Crypto", "Q&A", "Regional", "Other",
]

# name: (category, description)
SITE_INFO = {
    "1337x": ("Other", "Torrent index - uploader profiles"),
    "2Dimensions": ("Art & Design", "Character art community"),
    "7Cups": ("Social", "Peer emotional support chat"),
    "8tracks": ("Music", "Playlist sharing"),
    "9GAG": ("Social", "Meme sharing"),
    "APClips": ("Adult", "Adult clip store"),
    "About.me": ("Social", "Personal landing pages"),
    "Academia.edu": ("Education", "Academic paper sharing"),
    "AdmireMe.Vip": ("Adult", "Adult creator subscriptions"),
    "Airbit": ("Music", "Beat marketplace for producers"),
    "Airliners": ("Photo", "Aviation photography"),
    "Alik.cz": ("Regional", "Czech children's community"),
    "AllMyLinks": ("Social", "Link-in-bio pages"),
    "Anilist": ("Video", "Anime and manga tracking"),
    "Apple Developer": ("Developer", "Apple developer forums"),
    "Apple Discussions": ("Q&A", "Apple support community"),
    "Archive of Our Own": ("Books & Writing", "Fan-fiction archive (AO3)"),
    "Archive.org": ("Other", "Internet Archive user accounts"),
    "ArtStation": ("Art & Design", "Portfolio site for game/film artists"),
    "Asciinema": ("Developer", "Terminal session recordings"),
    "Ask Fedora": ("Q&A", "Fedora Linux Q&A forum"),
    "AskFM": ("Q&A", "Anonymous question and answer"),
    "Audiojungle": ("Music", "Envato royalty-free audio market"),
    "Autofrage": ("Q&A", "German car Q&A"),
    "Avizo": ("Shopping", "Czech classifieds"),
    "BLIP.fm": ("Music", "Music sharing"),
    "BOOTH": ("Shopping", "Japanese creator marketplace (pixiv)"),
    "Bandcamp": ("Music", "Independent music sales"),
    "Bazar.cz": ("Shopping", "Czech classifieds"),
    "Behance": ("Art & Design", "Adobe creative portfolios"),
    "Bezuzyteczna": ("Social", "Polish humour site"),
    "BiggerPockets": ("Finance & Crypto", "Real-estate investing community"),
    "BioHacking": ("Forum", "Biohacking discussion forum"),
    "BitBucket": ("Developer", "Atlassian git hosting"),
    "Bitwarden Forum": ("Forum", "Bitwarden password manager community"),
    "Blogger": ("Blogging", "Google's blog platform"),
    "BodyBuilding": ("Sport & Outdoors", "Bodybuilding.com forums"),
    "BongaCams": ("Adult", "Adult webcam site"),
    "Bookcrossing": ("Books & Writing", "Book-sharing community"),
    "BraveCommunity": ("Forum", "Brave browser community"),
    "BuyMeACoffee": ("Business", "Creator tipping"),
    "BuzzFeed": ("Social", "BuzzFeed community accounts"),
    "CGTrader": ("Art & Design", "3D model marketplace"),
    "CNET": ("Forum", "CNET tech forums"),
    "CSSBattle": ("Developer", "CSS code-golf game"),
    "CTAN": ("Developer", "TeX package archive contributors"),
    "Caddy Community": ("Forum", "Caddy web server forum"),
    "Car Talk Community": ("Forum", "Car advice forum"),
    "Carbonmade": ("Art & Design", "Portfolio hosting"),
    "Career.habr": ("Business", "Russian tech careers (Habr)"),
    "Championat": ("Sport & Outdoors", "Russian sports news"),
    "Chaos": ("Developer", "Chaos Computer Club community"),
    "Chaturbate": ("Adult", "Adult webcam site"),
    "Chess": ("Gaming", "Chess.com player profiles"),
    "Choice Community": ("Forum", "Choice of Games forum"),
    "Clapper": ("Video", "Short-video app"),
    "CloudflareCommunity": ("Forum", "Cloudflare community forum"),
    "Clozemaster": ("Education", "Language-learning game"),
    "Clubhouse": ("Social", "Audio chat rooms"),
    "Code Snippet Wiki": ("Developer", "Code snippet wiki"),
    "Codeberg": ("Developer", "Non-profit git hosting"),
    "Codecademy": ("Education", "Coding courses"),
    "Codechef": ("Developer", "Competitive programming"),
    "Codeforces": ("Developer", "Competitive programming"),
    "Codepen": ("Developer", "Front-end code playground"),
    "Coders Rank": ("Developer", "Developer ranking profiles"),
    "Coderwall": ("Developer", "Developer tips community"),
    "Codewars": ("Developer", "Coding kata practice"),
    "Coinvote": ("Finance & Crypto", "Crypto coin voting"),
    "ColourLovers": ("Art & Design", "Colour palette community"),
    "Contently": ("Business", "Writer portfolios"),
    "Coroflot": ("Art & Design", "Design portfolios and jobs"),
    "Cracked.io": ("Security", "Cracking/leaks forum"),
    "Crevado": ("Art & Design", "Portfolio hosting"),
    "Crowdin": ("Developer", "Localisation platform"),
    "Cryptomator Forum": ("Forum", "Cryptomator encryption community"),
    "Cults3D": ("Art & Design", "3D-printing model marketplace"),
    "DEV Community": ("Developer", "dev.to developer blogging"),
    "DMOJ": ("Developer", "Online judge for programming"),
    "DailyMotion": ("Video", "Video hosting"),
    "Dealabs": ("Shopping", "French deals community"),
    "DeviantART": ("Art & Design", "Art community"),
    "Discogs": ("Music", "Music database and marketplace"),
    "Discord": ("Social", "Discord invite/vanity links"),
    "Discuss.Elastic.co": ("Forum", "Elasticsearch community"),
    "Disqus": ("Social", "Comment system profiles"),
    "Docker Hub": ("Developer", "Container image registry"),
    "Dribbble": ("Art & Design", "Design showcase"),
    "Duolingo": ("Education", "Language learning"),
    "Eintracht Frankfurt Forum": ("Sport & Outdoors", "Football club fan forum"),
    "Envato Forum": ("Forum", "Envato marketplace forum"),
    "Erome": ("Adult", "Adult media sharing"),
    "Exposure": ("Photo", "Photo storytelling"),
    "EyeEm": ("Photo", "Photo community and licensing"),
    "F3.cool": ("Q&A", "Anonymous Q&A app"),
    "Fameswap": ("Business", "Social account marketplace"),
    "Fandom": ("Other", "Wiki hosting (Wikia)"),
    "Finanzfrage": ("Q&A", "German finance Q&A"),
    "Fiverr": ("Business", "Freelance gig marketplace"),
    "Flickr": ("Photo", "Photo sharing"),
    "Flightradar24": ("Other", "Flight tracking community"),
    "Flipboard": ("Social", "News magazine app"),
    "Football": ("Sport & Outdoors", "Football fan community"),
    "FortniteTracker": ("Gaming", "Fortnite stats"),
    "Forum Ophilia": ("Forum", "Discussion forum"),
    "Fosstodon": ("Fediverse", "Mastodon instance for FOSS"),
    "Freelance.habr": ("Business", "Russian freelance (Habr)"),
    "Freelancer": ("Business", "Freelance marketplace"),
    "Freesound": ("Music", "Creative-commons sound library"),
    "GNOME VCS": ("Developer", "GNOME GitLab"),
    "GaiaOnline": ("Social", "Anime-themed community"),
    "Gamespot": ("Gaming", "Games news and community"),
    "GeeksforGeeks": ("Developer", "Programming tutorials"),
    "Genius (Artists)": ("Music", "Lyrics site - artist pages"),
    "Genius (Users)": ("Music", "Lyrics site - user profiles"),
    "Gettr": ("Social", "Microblogging"),
    "Giant Bomb": ("Gaming", "Games wiki and community"),
    "Giphy": ("Social", "GIF hosting"),
    "GitBook": ("Developer", "Documentation hosting"),
    "GitHub": ("Developer", "Code hosting"),
    "GitLab": ("Developer", "Code hosting"),
    "Gitee": ("Developer", "Chinese code hosting"),
    "GoodReads": ("Books & Writing", "Book reviews and reading lists"),
    "Google Play": ("Developer", "Android app developer pages"),
    "Gradle": ("Developer", "Gradle plugin portal"),
    "Grailed": ("Shopping", "Menswear resale"),
    "Gravatar": ("Social", "Globally recognised avatars (WordPress)"),
    "Gumroad": ("Business", "Creator digital sales"),
    "Gutefrage": ("Q&A", "German Q&A"),
    "HackTheBox": ("Security", "Pentesting labs"),
    "Hackaday": ("Developer", "Hardware hacking projects"),
    "HackenProof (Hackers)": ("Security", "Bug bounty platform"),
    "HackerEarth": ("Developer", "Coding challenges"),
    "HackerNews": ("Developer", "Y Combinator news forum"),
    "HackerOne": ("Security", "Bug bounty platform"),
    "HackerRank": ("Developer", "Coding challenges"),
    "Harvard Scholar": ("Education", "Harvard scholar pages"),
    "Hashnode": ("Developer", "Developer blogging"),
    "Heavy-R": ("Adult", "Adult video site"),
    "Holopin": ("Developer", "Developer badge boards"),
    "Houzz": ("Other", "Home design and renovation"),
    "HubPages": ("Blogging", "Article publishing"),
    "Hubski": ("Social", "Link aggregator"),
    "HudsonRock": ("Security", "Infostealer breach lookup"),
    "IFTTT": ("Developer", "Automation applets"),
    "IRC-Galleria": ("Regional", "Finnish social network"),
    "Icons8 Community": ("Art & Design", "Icons8 forum"),
    "Image Fap": ("Adult", "Adult image site"),
    "ImgUp.cz": ("Photo", "Czech image host"),
    "Imgur": ("Photo", "Image hosting"),
    "Instagram": ("Social", "Photo/video social network"),
    "Instructables": ("Other", "DIY project guides"),
    "Intigriti": ("Security", "Bug bounty platform"),
    "Ionic Forum": ("Forum", "Ionic framework forum"),
    "Issuu": ("Business", "Digital publishing"),
    "Itch.io": ("Gaming", "Indie game marketplace"),
    "Jellyfin Weblate": ("Developer", "Jellyfin translations"),
    "Jimdo": ("Other", "Website builder"),
    "Joplin Forum": ("Forum", "Joplin notes app forum"),
    "KEAKR": ("Music", "Hip-hop music social"),
    "Kaggle": ("Developer", "Data science competitions"),
    "Keybase": ("Security", "Encrypted identity/key directory"),
    "Kick": ("Video", "Live streaming"),
    "Kik": ("Social", "Messaging app"),
    "Kongregate": ("Gaming", "Browser games"),
    "LOR": ("Forum", "Linux.org.ru forum"),
    "Launchpad": ("Developer", "Ubuntu/Canonical code hosting"),
    "LeetCode": ("Developer", "Coding interview practice"),
    "LessWrong": ("Forum", "Rationality community"),
    "Letterboxd": ("Video", "Film diary and reviews"),
    "LibraryThing": ("Books & Writing", "Book cataloguing"),
    "Lichess": ("Gaming", "Free online chess"),
    "LinkedIn": ("Business", "Professional network"),
    "Linktree": ("Social", "Link-in-bio pages"),
    "Listed": ("Blogging", "Standard Notes blogging"),
    "LiveJournal": ("Blogging", "Blogging community"),
    "Lobsters": ("Developer", "Tech link aggregator"),
    "LottieFiles": ("Art & Design", "Animation assets"),
    "LushStories": ("Adult", "Erotic fiction"),
    "MMORPG Forum": ("Gaming", "MMORPG.com forums"),
    "Medium": ("Blogging", "Long-form publishing"),
    "Memrise": ("Education", "Language learning"),
    "Minecraft": ("Gaming", "Minecraft player names"),
    "MixCloud": ("Music", "DJ mixes and radio shows"),
    "Monkeytype": ("Gaming", "Typing test"),
    "Motherless": ("Adult", "Adult media site"),
    "Motorradfrage": ("Q&A", "German motorcycle Q&A"),
    "MyAnimeList": ("Video", "Anime and manga tracking"),
    "MyMiniFactory": ("Art & Design", "3D-printing models"),
    "Mydramalist": ("Video", "Asian drama tracking"),
    "Myspace": ("Social", "Legacy social network"),
    "NICommunityForum": ("Music", "Native Instruments forum"),
    "NationStates Nation": ("Gaming", "Nation simulation game"),
    "NationStates Region": ("Gaming", "Nation simulation game - regions"),
    "Naver": ("Regional", "Korean portal"),
    "Needrom": ("Developer", "Android ROM downloads"),
    "Newgrounds": ("Art & Design", "Flash games, animation, art"),
    "Nextcloud Forum": ("Forum", "Nextcloud community"),
    "Nightbot": ("Video", "Twitch/YouTube chat bot"),
    "Ninja Kiwi": ("Gaming", "Bloons games developer community"),
    "NitroType": ("Gaming", "Typing race game"),
    "NotABug.org": ("Developer", "Libre git hosting"),
    "Nyaa.si": ("Other", "Anime torrent index"),
    "OGUsers": ("Security", "Username trading forum"),
    "OpenStreetMap": ("Other", "Map contributors"),
    "Opensource": ("Developer", "Opensource.com authors"),
    "OurDJTalk": ("Music", "DJ forum"),
    "PCGamer": ("Gaming", "PC Gamer forums"),
    "PSNProfiles.com": ("Gaming", "PlayStation trophy tracking"),
    "Packagist": ("Developer", "PHP package registry"),
    "Pastebin": ("Developer", "Text paste hosting"),
    "Patreon": ("Business", "Creator memberships"),
    "PentesterLab": ("Security", "Pentest training"),
    "PepperIT": ("Forum", "Italian tech forum"),
    "Periscope": ("Video", "Legacy live streaming"),
    "Pinkbike": ("Sport & Outdoors", "Mountain biking"),
    "Pinterest": ("Social", "Image pinboards"),
    "PlayStore": ("Developer", "Android app developer pages"),
    "PocketStars": ("Adult", "Adult creator platform"),
    "Pokemon Showdown": ("Gaming", "Pokemon battle simulator"),
    "Polarsteps": ("Other", "Travel tracking"),
    "Polygon": ("Gaming", "Games/culture news"),
    "Polymart": ("Gaming", "Minecraft plugin market"),
    "Pornhub": ("Adult", "Adult video site"),
    "ProductHunt": ("Business", "Product launches"),
    "PromoDJ": ("Music", "Russian DJ community"),
    "PyPi": ("Developer", "Python package index"),
    "Rajce.net": ("Photo", "Czech photo albums"),
    "Rate Your Music": ("Music", "Music ratings database"),
    "Rclone Forum": ("Forum", "rclone community"),
    "Redbubble": ("Shopping", "Print-on-demand art"),
    "Reddit": ("Social", "Discussion communities"),
    "Reisefrage": ("Q&A", "German travel Q&A"),
    "Replit.com": ("Developer", "Online IDE"),
    "ResearchGate": ("Education", "Researcher network"),
    "ReverbNation": ("Music", "Musician promotion"),
    "Roblox": ("Gaming", "Roblox player profiles"),
    "RoyalCams": ("Adult", "Adult webcam site"),
    "RubyGems": ("Developer", "Ruby package registry"),
    "Rumble": ("Video", "Video hosting"),
    "RuneScape": ("Gaming", "RuneScape hiscores"),
    "SWAPD": ("Business", "Social account marketplace"),
    "Sbazar.cz": ("Shopping", "Czech classifieds"),
    "Scratch": ("Education", "MIT kids' coding community"),
    "Scribd": ("Books & Writing", "Document sharing"),
    "ShitpostBot5000": ("Social", "Meme generator community"),
    "Shpock": ("Shopping", "Classifieds app"),
    "Signal": ("Social", "Signal username links"),
    "Sketchfab": ("Art & Design", "3D model viewer"),
    "Slack": ("Business", "Workspace subdomains"),
    "Slant": ("Q&A", "Product recommendation votes"),
    "Slashdot": ("Developer", "Tech news forum"),
    "SlideShare": ("Business", "Presentation sharing"),
    "Slides": ("Business", "Slides.com presentations"),
    "SmugMug": ("Photo", "Photo hosting"),
    "Smule": ("Music", "Karaoke app"),
    "Snapchat": ("Social", "Snapchat public profiles"),
    "SoundCloud": ("Music", "Audio sharing"),
    "SourceForge": ("Developer", "Open-source project hosting"),
    "SoylentNews": ("Developer", "Tech news forum"),
    "Speedrun.com": ("Gaming", "Speedrun leaderboards"),
    "Spells8": ("Other", "Witchcraft community"),
    "Splice": ("Music", "Sample library"),
    "Splits.io": ("Gaming", "Speedrun splits"),
    "Sporcle": ("Gaming", "Trivia quizzes"),
    "Sportlerfrage": ("Q&A", "German sports Q&A"),
    "SportsRU": ("Sport & Outdoors", "Russian sports news"),
    "Spotify": ("Music", "Music streaming user pages"),
    "Star Citizen": ("Gaming", "Star Citizen citizen pages"),
    "Steam Community (Group)": ("Gaming", "Steam groups"),
    "Steam Community (User)": ("Gaming", "Steam user profiles"),
    "Strava": ("Sport & Outdoors", "Running/cycling tracking"),
    "SublimeForum": ("Forum", "Sublime Text forum"),
    "TETR.IO": ("Gaming", "Online Tetris"),
    "TLDR Legal": ("Developer", "Software licence summaries"),
    "TRAKTRAIN": ("Music", "Beat marketplace"),
    "Telegram": ("Social", "Telegram public usernames"),
    "Tellonym.me": ("Q&A", "Anonymous messages"),
    "Tenor": ("Social", "GIF search"),
    "ThemeForest": ("Developer", "Envato theme market"),
    "TikTok": ("Video", "Short-video social network"),
    "TnAFlix": ("Adult", "Adult video site"),
    "TorrentGalaxy": ("Other", "Torrent index"),
    "TradingView": ("Finance & Crypto", "Charting and trading ideas"),
    "Trakt": ("Video", "TV/film tracking"),
    "TrashboxRU": ("Developer", "Russian software downloads"),
    "Trawelling": ("Other", "Train travel logging"),
    "Trello": ("Business", "Kanban boards"),
    "TryHackMe": ("Security", "Cyber-security training"),
    "Tumblr": ("Blogging", "Microblogging"),
    "Tuna": ("Music", "Music community"),
    "Tweakers": ("Forum", "Dutch tech community"),
    "Twitch": ("Video", "Live streaming"),
    "Twitter": ("Social", "Microblogging (X)"),
    "Typeracer": ("Gaming", "Typing race game"),
    "Ultimate-Guitar": ("Music", "Guitar tabs"),
    "Unsplash": ("Photo", "Free stock photos"),
    "Untappd": ("Other", "Beer check-ins"),
    "VK": ("Social", "Russian social network"),
    "VLR": ("Gaming", "Valorant esports forum"),
    "VSCO": ("Photo", "Photo editing and sharing"),
    "Velomania": ("Sport & Outdoors", "Russian cycling forum"),
    "Venmo": ("Finance & Crypto", "Payments app"),
    "Vero": ("Social", "Ad-free social network"),
    "Vimeo": ("Video", "Video hosting"),
    "VirusTotal": ("Security", "Malware scanning community"),
    "WICG Forum": ("Developer", "Web Incubator community group"),
    "Warrior Forum": ("Business", "Internet marketing forum"),
    "Wattpad": ("Books & Writing", "Story sharing"),
    "WebNode": ("Other", "Website builder"),
    "Weblate": ("Developer", "Translation platform"),
    "Weebly": ("Other", "Website builder"),
    "WhonixForum": ("Security", "Whonix privacy OS forum"),
    "Wikidot": ("Other", "Wiki hosting"),
    "Wikipedia": ("Education", "Wikipedia user pages"),
    "Windy": ("Other", "Weather community"),
    "Wix": ("Other", "Website builder"),
    "WolframalphaForum": ("Forum", "Wolfram community"),
    "WordPress": ("Blogging", "WordPress.com blogs"),
    "WordPressOrg": ("Developer", "WordPress.org profiles"),
    "Wykop": ("Social", "Polish link aggregator"),
    "Xbox Gamertag": ("Gaming", "Xbox gamertag lookup"),
    "Xvideos": ("Adult", "Adult video site"),
    "YandexMusic": ("Music", "Yandex music streaming"),
    "YouNow": ("Video", "Live streaming"),
    "YouPic": ("Photo", "Photo community"),
    "YouPorn": ("Adult", "Adult video site"),
    "YouTube": ("Video", "Video channels"),
    "akniga": ("Books & Writing", "Russian audiobooks"),
    "authorSTREAM": ("Business", "Presentation sharing"),
    "babyRU": ("Forum", "Russian parenting community"),
    "babyblogRU": ("Forum", "Russian parenting blog"),
    "chaos.social": ("Fediverse", "Mastodon instance"),
    "couchsurfing": ("Social", "Travel hospitality network"),
    "d3RU": ("Forum", "Russian D3 forum"),
    "dailykos": ("Blogging", "US political blog community"),
    "datingRU": ("Dating", "Russian dating site"),
    "devRant": ("Developer", "Developer venting community"),
    "drive2": ("Other", "Russian car owners' community"),
    "eGPU": ("Forum", "External GPU forum"),
    "eintracht": ("Sport & Outdoors", "Football club fan forum"),
    "fixya": ("Q&A", "Product repair Q&A"),
    "fl": ("Business", "Russian freelance (fl.ru)"),
    "forum_guns": ("Forum", "Russian firearms forum"),
    "forumhouseRU": ("Forum", "Russian home-building forum"),
    "freecodecamp": ("Education", "Free coding curriculum"),
    "furaffinity": ("Art & Design", "Furry art community"),
    "geocaching": ("Sport & Outdoors", "Geocaching profiles"),
    "gfycat": ("Social", "GIF hosting (defunct)"),
    "habr": ("Developer", "Russian tech blog community"),
    "hackster": ("Developer", "Hardware projects"),
    "hunting": ("Forum", "Russian hunting forum"),
    "iMGSRC.RU": ("Photo", "Russian image hosting"),
    "igromania": ("Gaming", "Russian games site"),
    "interpals": ("Social", "Pen-pal network"),
    "irecommend": ("Shopping", "Russian product reviews"),
    "jbzd.com.pl": ("Social", "Polish meme site"),
    "jeuxvideo": ("Gaming", "French games community"),
    "kwork": ("Business", "Russian freelance marketplace"),
    "last.fm": ("Music", "Music scrobbling"),
    "leasehackr": ("Finance & Crypto", "Car leasing forum"),
    "livelib": ("Books & Writing", "Russian book community"),
    "mastodon.cloud": ("Fediverse", "Mastodon instance"),
    "mastodon.social": ("Fediverse", "Flagship Mastodon instance"),
    "mastodon.xyz": ("Fediverse", "Mastodon instance"),
    "mercadolivre": ("Shopping", "Brazilian marketplace"),
    "minds": ("Social", "Open-source social network"),
    "moikrug": ("Business", "Russian tech careers"),
    "mstdn.io": ("Fediverse", "Mastodon instance"),
    "nairaland.com": ("Forum", "Nigerian forum"),
    "nnRU": ("Regional", "Russian regional portal"),
    "note": ("Blogging", "Japanese blogging (note.com)"),
    "npm": ("Developer", "JavaScript package registry"),
    "opennet": ("Developer", "Russian open-source news"),
    "osu!": ("Gaming", "Rhythm game profiles"),
    "phpRU": ("Forum", "Russian PHP forum"),
    "pikabu": ("Social", "Russian Reddit-like community"),
    "pr0gramm": ("Social", "German image board"),
    "prog.hu": ("Developer", "Hungarian programming forum"),
    "queer.af": ("Fediverse", "Mastodon instance"),
    "satsisRU": ("Forum", "Russian satellite TV forum"),
    "sessionize": ("Business", "Conference speaker profiles"),
    "skyrock": ("Blogging", "French blogging"),
    "social.tchncs.de": ("Fediverse", "Mastodon instance"),
    "spletnik": ("Social", "Russian celebrity gossip"),
    "svidbook": ("Social", "Russian social site"),
    "toster": ("Q&A", "Russian tech Q&A"),
    "uid": ("Other", "Russian ID lookup"),
    "wiki.vg": ("Developer", "Minecraft protocol wiki"),
    "xHamster": ("Adult", "Adult video site"),
    "znanylekarz.pl": ("Other", "Polish doctor directory"),
    "Facebook": ("Social", "Social network"),
    "Tinder": ("Dating", "Dating app"),
    "OnlyFans": ("Adult", "Creator subscriptions"),
    "Threads": ("Social", "Meta's microblogging"),
    "Bluesky": ("Social", "Decentralised microblogging"),
    "Etsy": ("Shopping", "Handmade goods marketplace"),
    "eBay": ("Shopping", "Auction marketplace"),
    "Quora": ("Q&A", "Question and answer"),
    "Stack Overflow": ("Developer", "Programming Q&A"),
    "Substack": ("Blogging", "Newsletter publishing"),
    "Ko-fi": ("Business", "Creator tipping"),
    "Cash App": ("Finance & Crypto", "Payments app"),
    "PayPal": ("Finance & Crypto", "Payments"),
    "Bitcoin Forum": ("Finance & Crypto", "bitcointalk.org"),
    "Mastodon": ("Fediverse", "Mastodon instance"),
    "Pixiv": ("Art & Design", "Japanese illustration community"),
    "Tripadvisor": ("Other", "Travel reviews"),
    "Yelp": ("Other", "Local business reviews"),
    "Vivino": ("Other", "Wine ratings"),
    "Peloton": ("Sport & Outdoors", "Fitness"),
    "Garmin Connect": ("Sport & Outdoors", "Fitness tracking"),
    "Wikimapia": ("Other", "Collaborative map"),
    "Freelancermap": ("Business", "Freelance marketplace"),
    "Upwork": ("Business", "Freelance marketplace"),
    "AngelList": ("Business", "Start-up network"),
    "Crunchbase": ("Business", "Company database"),
    "Xing": ("Business", "German professional network"),
}

# Sites where Sherlock is known to report "Claimed" for usernames that do not
# exist (bot walls, redirects to a generic page, soft-404s, rate limiting).
# Editable in the app under Settings > False-positive sites.
DEFAULT_FLAKY_SITES = [
    "Xbox Gamertag", "Kik", "Wattpad", "Fiverr", "Spotify", "Facebook",
    "Instagram", "TikTok", "Chaturbate", "Kongregate", "Naver", "Vero",
    "Slack", "VK", "Snapchat", "Pinterest", "LinkedIn", "Twitter", "Roblox",
    "Tumblr", "Freelancer", "Genius (Users)", "Trello", "Venmo", "ImgUp.cz",
    "Pornhub", "Discord", "Telegram", "Signal", "Minecraft", "RuneScape",
    "Duolingo", "Periscope", "gfycat", "Clubhouse", "Fameswap", "SWAPD",
]

_KEYWORD_CATEGORIES = [
    (r"forum|community|discuss|talk\b", "Forum"),
    (r"mastodon|mstdn|fediverse|pleroma|misskey|\.social", "Fediverse"),
    (r"cam|porn|xxx|adult|hentai|fap|nsfw|erot|sex", "Adult"),
    (r"git|code|dev|hack|package|npm|pypi|gem|crate|\.io/|stack", "Developer"),
    (r"game|gaming|steam|xbox|play|speedrun|minecraft|chess|osu|tetr", "Gaming"),
    (r"music|dj|sound|beat|audio|\.fm|bandcamp|song", "Music"),
    (r"video|tube|stream|tv|film|anime|drama|twitch", "Video"),
    (r"photo|pic|img|image|flickr|cam\b", "Photo"),
    (r"art|design|3d|draw|deviant|dribbble|behance|sketch", "Art & Design"),
    (r"blog|journal|medium|wordpress|tumblr|note", "Blogging"),
    (r"book|read|story|fiction|writ|lib", "Books & Writing"),
    (r"dating|date|tinder|match", "Dating"),
    (r"shop|market|bazar|store|sell|buy|deal|classif", "Shopping"),
    (r"sport|bike|run|fit|hunt|fish|climb|ski|strava", "Sport & Outdoors"),
    (r"crypto|coin|bitcoin|trading|invest|finance|pay|bank", "Finance & Crypto"),
    (r"frage|ask|question|answer|q&a|tellonym", "Q&A"),
    (r"learn|edu|school|academ|scholar|course|univers|wiki", "Education"),
    (r"security|sec\b|bounty|pentest|exploit|virus|leak|crack", "Security"),
    (r"freelance|work|job|career|business|linkedin|xing|company", "Business"),
    (r"\.ru\b|\.cz\b|\.pl\b|\.hu\b|\.de\b|\.fr\b|\.jp\b|\.kr\b|\.br\b", "Regional"),
    (r"social|friend|chat|meet|network|link", "Social"),
]

_TLD_DESC = {
    ".ru": "Russian site", ".cz": "Czech site", ".pl": "Polish site",
    ".de": "German site", ".fr": "French site", ".jp": "Japanese site",
    ".kr": "Korean site", ".br": "Brazilian site", ".hu": "Hungarian site",
    ".it": "Italian site", ".es": "Spanish site", ".nl": "Dutch site",
    ".ua": "Ukrainian site", ".tr": "Turkish site", ".in": "Indian site",
}


def _norm(name):
    return re.sub(r"[^a-z0-9]", "", (name or "").lower())


_NORM_INFO = {_norm(k): v for k, v in SITE_INFO.items()}
_NORM_FLAKY = {_norm(k) for k in DEFAULT_FLAKY_SITES}


def _domain(info):
    for key in ("urlMain", "url"):
        u = (info or {}).get(key)
        if u:
            try:
                return (urlparse(u).netloc or "").lower()
            except Exception:
                pass
    return ""


def lookup(name, info=None):
    """Return (category, description) for a Sherlock site.

    `info` is the site's data.json entry (used for isNSFW and the domain when
    the name is not in the hand-written map).
    """
    info = info or {}
    hit = _NORM_INFO.get(_norm(name))
    if hit:
        cat, desc = hit
        if info.get("isNSFW") and cat != "Adult":
            desc += " (flagged NSFW)"
        return cat, desc

    dom = _domain(info)
    text = f"{name} {dom}".lower()
    if info.get("isNSFW"):
        cat = "Adult"
    else:
        cat = "Other"
        for pat, c in _KEYWORD_CATEGORIES:
            if re.search(pat, text):
                cat = c
                break
    desc = ""
    for tld, d in _TLD_DESC.items():
        if dom.endswith(tld):
            desc = d
            break
    if not desc:
        desc = dom or "No description available"
    return cat, desc


def is_default_flaky(name):
    return _norm(name) in _NORM_FLAKY


def norm_name(name):
    return _norm(name)
